name = "sociologyprograms-website"
compatibility_date = "2024-01-01"

[env.production]
# Replace with your actual Cloudflare account ID
# You can find this in your Cloudflare dashboard
account_id = "your-account-id-here"

# Static site configuration
[site]
bucket = "./"

# Observability configuration
[observability]
enabled = true

[observability.logs]
enabled = false

# Build configuration
[build]
command = ""
cwd = "./"
upload_dir = "./"

# Environment variables
[vars]
ENVIRONMENT = "production"
